import {
  Admin,
  Ambev,
  App360,
  CashBuild,
  CnpMidia,
  Erp360,
  Lacosta,
  Metaverse,
  Zytro,
} from "../../public/Assets/Works/index";

export const items = [
  {
    titulo: "Ambev - Tergo project",
    video: Ambev,
    alt: "Social media agency",
    id: 9,
    github: "https://github.com/ThiagoC0STA/ambev-tergo",
    techs: "Cubit, flutter, Clean Architecture, Firebase, Figma",
  },
  {
    titulo: "Cnp Midia - I am the CEO 🫡",
    img: CnpMidia,
    url: "https://cnpmidia.com/",
    alt: "Social media agency",
    id: 8,
    github: "https://github.com/ThiagoC0STA/cnpmidia",
    techs: "HTML5, CSS3, JavaScript, Figma, Tailwind css, Design advanced",
  },
  {
    titulo: "La costa",
    img: Lacosta,
    url: "https://lacostacorretora.netlify.app/",
    alt: "Insurance broker website",
    github: "https://github.com/ThiagoC0STA/lacosta",
    id: 4,
    techs: "HTML5 CSS3 JavaScript, Figma",
  },
  {
    titulo: "Zytro - (Web and mobile app)",
    img: Zytro,
    url: "https://www.zytro.co.uk/",
    alt: "A 3d app design system",
    id: 7,
    techs:
      "HTML5, CSS3, JavaScript, React, Next.js, Figma, Tailwind css, React native",
  },
  {
    titulo: "360 ERP - (Web)",
    img: Erp360,
    url: "https://app.360erp.com.br/",
    alt: "Full erp system",
    id: 1,
    techs: "HTML5, CSS3, JavaScript, React, Next.js, Figma, Tailwind css",
  },
  {
    titulo: "360 ERP - (App)",
    img: App360,
    url: "https://apps.apple.com/br/app/360-erp/id1540511289",
    alt: "Full erp system",
    id: 6,
    techs: "Flutter, Dart, C++, swift, kotlin, Figma, Tailwind css",
  },

  {
    titulo: "Metaverse - Animation study",
    img: Metaverse,
    url: "https://metaverse-landing-page-three.vercel.app/",
    alt: "Study for animations",
    github: "https://github.com/ThiagoC0STA/Metaverse-landing-page",
    id: 2,
    techs:
      "HTML5, CSS3, JavaScript, React, Next.js, Figma, Styled components, Framer-Motion",
  },
  {
    titulo: "Cash build - Real Estate",
    img: CashBuild,
    url: "https://www.cashbuild.com.br/",
    alt: "Real estate website",
    github: "https://github.com/ThiagoC0STA/Cash-build",
    id: 3,
    techs:
      "HTML5, CSS3, JavaScript, React, Figma, Next.js, Typescript and Styled components",
  },
  {
    titulo: "Shoppy - Admin Dashboard",
    img: Admin,
    url: "https://admin-dashboard-thiagoc0sta.vercel.app/",
    alt: "Admin dashboard",
    github: "https://github.com/ThiagoC0STA/admin-dashboard",
    id: 5,
    techs: "HTML5, CSS3, JavaScript, React, Tailwind Css and Syncfusion",
  },
];
