export { default as Header } from "./Header/Header";
export { default as Main } from "./Main/Main";
export { default as About } from "./About/About";
export { default as Experience } from "./Experience/Experience";
export { default as Offer } from "./Offer/Offer";
export { default as Works } from "./Works/Works";
export { default as Contact } from "./Contact/Contact";
export { default as Footer } from "./Footer/Footer";
export { default as LoadingAnimation } from "./LoadingAnimation/LoadingAnimation";
